[workspace]
resolver = "3"
members = [
	"code_generation",
	"estree",
	"from",
	"lexer",
	"parser",
	"proto",
	"tests",
	"token",
	"transpiler"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
